###
GET http://localhost:8080/api/course/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInN1YiI6InBhYmxvIiwiaWF0IjoxNzUwOTA0MTQwLCJleHAiOjE3NTA5OTA1NDB9._MQbVd7FG_XZ-ruAioBy7NuhQ6fCtcQMMVjIP1LkCtgEpxg4Qgw-JgG255hDi9Dc

###
POST http://localhost:8080/api/course
Content-Type: application/json

{
    "name":"Filosofia ",
    "description":"Primeros avances filosoficos de la edad griega...",
    "maxAmount":25,
    "phone":"3138176076",
    "professor_id": 2
}
###
DELETE http://localhost:8080/api/course/1

###
PUT http://localhost:8080/api/course/1
Content-Type: application/json

{
    "firstName":"Juan",
    "lastName":"Morales Artunduaga",
    "email":"1034776660@gmail.com",
    "phone":"3138176076"
}
