###
GET http://localhost:8080/api/student
#Authorization: Basic user:02d2d136-b766-4bab-8665-c68f473c984d

###
POST http://localhost:8080/api/student
Authorization: Basic user:02d2d136-b766-4bab-8665-c68f473c984d
Content-Type: application/json

{
    "firstName":"Juan",
    "lastName":"Morales Artunduaga",
    "email":"1034776660@gmail.com",
    "phone":"3138176076"
}
###
DELETE http://localhost:8080/api/student/1
