###
GET http://localhost:8080/api/professor


###
POST http://localhost:8080/api/professor
Content-Type: application/json

{
    "firstName":"Rufino",
    "lastName":"Cuellar",
    "email":"manolo123@gmail.com",
    "departament" : "Caqueta"
}
###
DELETE http://localhost:8080/api/professor/1

###
PUT http://localhost:8080/api/professor/1
Content-Type: application/json

{
    "firstName":"Juan",
    "lastName":"Morales Artunduaga",
    "email":"1034776660@gmail.com",
    "phone":"3138176076"
}
