###
GET http://localhost:8080/api/professor
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInN1YiI6InBhYmxvIiwiaWF0IjoxNzUwOTA0NDU4LCJleHAiOjE3NTA5OTA4NTh9.xuqvxoa2pS28bVANFW03F7CS09hAasTkik26ciCEDy5fX_-oTiWaHwiN26Wi0Cza

###
POST http://localhost:8080/api/professor
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInN1YiI6InBhYmxvIiwiaWF0IjoxNzUwOTA0MTQwLCJleHAiOjE3NTA5OTA1NDB9._MQbVd7FG_XZ-ruAioBy7NuhQ6fCtcQMMVjIP1LkCtgEpxg4Qgw-JgG255hDi9Dc
Content-Type: application/json

{
    "firstName":"Ramiro",
    "lastName":"Falla",
    "email":"ramiroo@gmail.com",
    "departament" : "Caqueta"
}
###
DELETE http://localhost:8080/api/professor/1

###
PUT http://localhost:8080/api/professor/1
Content-Type: application/json

{
    "firstName":"Juan",
    "lastName":"Morales Artunduaga",
    "email":"1034776660@gmail.com",
    "phone":"3138176076"
}
